openapi: 3.0.0
info:
  title: Combined API Specification
  version: 1.0.0
paths:
  /health:
    get:
      summary: Check health
      responses:
        '200':
          description: Health check successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseDto'
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
components:
  schemas:
    HealthCheckDetail:
      type: object
      properties:
        message:
          type: string
        meta:
          type: object
    ApiResponseDto:
      type: object
      properties:
        success:
          type: boolean
          default: true
        data:
          $ref: '#/components/schemas/HealthCheckDetail'
        message:
          type: string