openapi: 3.0.0
info:
  title: Combined API Specification
  version: 1.0.0
  description: This is a combined API specification including health check and other endpoints.
paths:
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: Health check successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseDto'
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
components:
  schemas:
    ApiResponseDto:
      type: object
      properties:
        success:
          type: boolean
        data:
          type: object
          $ref: '#/components/schemas/HealthCheckDetail'
        message:
          type: string
    HealthCheckDetail:
      type: object
      properties:
        message:
          type: string
        meta:
          type: object
          properties: {}
servers:
  - url: https://api.example.com/v1