openapi: 3.0.0
info:
  title: User Registration API
  version: 1.0.0
  description: API to register a user
paths:
  /register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: User successfully registered
        '404':
          description: Not found
        '500':
          description: Internal server error
servers:
  - url: https://api.example.com/v1