openapi: 3.0.0
info:
  title: Combined API Specification
  version: 1.0.0
paths:
  /health:
    get:
      summary: Health Check
      responses:
        '200':
          description: Health check successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseDto'
  /create:
    post:
      summary: Create Pipeline
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PushWorkflowDto'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseDto'
        '503':
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseDto'
      parameters:
      - in: header
        name: x-organization-id
        schema:
          type: string
        description: Organization ID
        required: true
      - in: header
        name: x-project-id
        schema:
          type: string
        description: Project ID
        required: true
      - in: header
        name: x-cluster-id
        schema:
          type: string
        description: Cluster ID
        required: true
      - in: header
        name: x-trace-id
        schema:
          type: string
        description: Trace ID
        required: true
components:
  schemas:
    ApiResponseDto:
      type: object
      properties:
        success:
          type: boolean
        data:
          type: object
        message:
          type: string
    HealthCheckDetail:
      type: object
      properties:
        message:
          type: string
        meta:
          type: object
          properties: {}
    PushWorkflowDto:
      type: object
      properties:
        pipelineType:
          type: string
        appId:
          type: string
        targetEnvId:
          type: string
        credentialId:
          type: string
        repositoryName:
          type: string
        branch:
          type: string
        triggers:
          type: array
          items:
            $ref: '#/components/schemas/Trigger'
        steps:
          type: array
          items:
            type: string
        workflowName:
          type: string
        fileName:
          type: string
      required:
      - pipelineType
      - appId
      - targetEnvId
      - credentialId
      - repositoryName
      - branch
      - triggers
      - steps
      - workflowName
      - fileName
    Trigger:
      type: object
      properties:
        type:
          type: string
      required:
      - type
