openapi: 3.0.0
info:
  title: Combined API Specification
  version: 1.0.0
paths:
  /health:
    get:
      summary: check health
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseDto'
components:
  schemas:
    ApiResponseDto:
      type: object
      properties:
        success:
          type: boolean
        data:
          $ref: '#/components/schemas/HealthCheckDetail'
        message:
          type: string
    HealthCheckDetail:
      type: object
      properties:
        message:
          type: string
        meta:
          type: object
