openapi: 3.0.0
info:
  title: Combined API Specification
  version: 1.0.0
paths:
  /health:
    get:
      summary: Check Health
      responses:
        '200':
          description: Health check successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseDto'
  /create:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                pipelineType:
                  type: string
                appId:
                  type: string
                targetEnvId:
                  type: string
                credentialId:
                  type: string
                repositoryName:
                  type: string
                branch:
                  type: string
                triggers:
                  type: array
                  items:
                    type: object
                steps:
                  type: array
                  items:
                    type: string
                workflowName:
                  type: string
                fileName:
                  type: string
              required:
              - pipelineType
              - appId
              - targetEnvId
              - credentialId
              - repositoryName
              - branch
              - triggers
              - steps
              - workflowName
              - fileName
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
                  message:
                    type: string
        '503':
          description: Service Unavailable
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
                  message:
                    type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
                  message:
                    type: string
      parameters:
      - name: x-organization-id
        in: header
        schema:
          type: string
        required: true
      - name: x-project-id
        in: header
        schema:
          type: string
        required: true
      - name: x-cluster-id
        in: header
        schema:
          type: string
        required: true
      - name: x-trace-id
        in: header
        schema:
          type: string
components:
  schemas:
    ApiResponseDto:
      type: object
      properties:
        success:
          type: boolean
        data:
          type: object
          $ref: '#/components/schemas/HealthCheckDetail'
        message:
          type: string
    HealthCheckDetail:
      type: object
      properties:
        message:
          type: string
        meta:
          type: object
          properties: {}
